import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("data/cleaned_tickets.csv")
total_tickets = len(df)
open_tickets = len(df[df["Status"] == "Open"])
closed_tickets = len(df[df["Status"] == "Closed"])
sla_breached = len(df[df["SLA_Status"] == "Breached"])
avg_resolution = round(df["Resolution_Hours"].mean(), 2)
print("Total Tickets:", total_tickets)
print("Open Tickets:", open_tickets)
print("Closed Tickets:", closed_tickets)
print("SLA Breached:", sla_breached)
print("Avg Resolution Hours:", avg_resolution)

dept_counts = df["Department"].value_counts().head(10)
plt.figure(figsize=(12,6))
dept_counts.plot(kind="bar")
plt.title("Tickets by Department")
plt.xlabel("Department")
plt.ylabel("Number of Tickets")
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.savefig("dashboard/tickets_by_department.png")
plt.close()

priority_counts = df["Priority"].value_counts()
plt.figure(figsize=(8,5))
priority_counts.plot(kind="bar")
plt.title("Tickets by Priority")
plt.xlabel("Priority")
plt.ylabel("Number of Tickets")
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig("dashboard/tickets_by_priority.png")
plt.close()

sla_counts = df["SLA_Status"].value_counts()
plt.figure(figsize=(6,5))
sla_counts.plot(kind="bar")
plt.title("SLA Compliance")
plt.xlabel("SLA Status")
plt.ylabel("Number of Tickets")
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig("dashboard/sla_status.png")
plt.close()

tags_series = df["Tags"].str.split(", ").explode()
top_tags = tags_series.value_counts().head(10)
plt.figure(figsize=(12,6))
top_tags.plot(kind="bar")
plt.title("Top Ticket Tags")
plt.xlabel("Tags")
plt.ylabel("Number of Tickets")
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.savefig("dashboard/top_tags.png")
plt.close()

print("Dashboard charts saved.")
